Fix misleading indentation warning:
sys/dev/vxge/vxgehal/vxgehal-virtualpath.c:5550:6: error: misleading indentation; statement is not part of the previous 'if' [-Werror,-Wmisleading-indentation]
                                        return (VXGE_HAL_ERR_EVENT_MRPCIM_CRITICAL);
                                        ^
sys/dev/vxge/vxgehal/vxgehal-virtualpath.c:5545:5: note: previous statement is here
                                if (!skip_alarms)
                                ^

Direct commit to stable/11, since vxge(4) has been removed from FreeBSD
12 and later.