fix up r361823, libprocstat zfs support, on powerpc
This fixes a build failure:
  In file included from .../zfs_context.h:104,
                   from .../libprocstat/zfs_defs.c:53:
  .../vm/vm_page.h:204: error: field 'md' has incomplete type

In this branch, on powerpc, struct md_page is visible only if either AIM
or BOOKE is defined.
This is a direct commit.